### ISSUE TITLE
Should verify other *_name tags

### ISSUE THREAD

**Issue by naoliv** [osmlab/checkin-checker#10]
A friend of mine did a check-in in one place where the Foursquare name was the same as OSM's `short_name` (so check-in checker thought that the place wasn't available in OSM).

Check-in checker should compare the Foursquare name with all the available `*_name` tags, to avoid receiving false-positives e-mails about missing places in OSM.

**Comment by iandees** [comment]
What are all the possible `*_name` tags? I've never heard of that tag before, and I'm sure there are tons of other tags we could check. Where should we stop?

**Comment by naoliv** [comment]
I guess this should match most of the places:

`alt_name`
`loc_name`
`name`
`official_name`
`short_name`

**Comment by iandees** [comment]
This has been a bit trickier than I thought because of the way I am querying Overpass. I'll have a bit more time to look at it this weekend.
