### ISSUE TITLE
Checkin checker can't find corresponding place

### ISSUE THREAD

**Issue by kkaefer** [osmlab/checkin-checker#11]
I just [checked in](https://foursquare.com/kkaefer/checkin/5721f479498e7b80090ba5ec), but the checker fails to find the [node that already exists](https://www.openstreetmap.org/node/871561394) despite having the same name. Maybe it doesn't ignore capitalization?

**Comment by iandees** [comment]
When I closed #10, I added a bunch more work to the Overpass query, so sometimes it times out and I don't handle that properly. I'll push a change that increases the timeout so this is less likely to happen.

**Comment by iandees** [comment]
This should be closed by fc52fca. If this happens again please feel free to reopen this.

**Comment by kkaefer** [comment]
Great, thanks!

**Comment by iandees** [comment]
Hah, this happened again just now (I added a log line and an alert for that log line).

You're just checking in to an area that has lots of data and happens to be slow in Overpass 😀 . Reducing the radius of the search doesn't seem to help very much, so I'm just going to bump up the timeout quite a bit.

**Comment by iandees** [comment]
Timeout is now 60 seconds as of 9b0cf92.
