### ISSUE TITLE
City Name in Venue Name Matches Administrative Boundary

### ISSUE THREAD

**Issue by talllguy** [osmlab/checkin-checker#12]
I [checked into a service shop](https://foursquare.com/talllguy/checkin/57274efc498e5dedce96ca4c) with its city name in the venue name (which is against Foursquare guidelines, but that's another issue). Checkin-checker dutifully [matched my checkin to the town boundary](https://www.openstreetmap.org/edit?relation=133446).

![2016-05-02 11_52_47-inbox elliott plack gmail com](https://cloud.githubusercontent.com/assets/1827881/14959253/75d34964-105c-11e6-828e-d9d843c25b0c.png)

**Comment by iandees** [comment]
Hm, two issues I see here:

1. The distance between `Glen Burnie` and `Service Collision Repair Glen Burnie` should be way bigger than it is. I wonder if I'm using the wrong fuzzy match algorithm or have parameters flipped around...
2. We should probably ignore administrative boundary matches altogether.

**Comment by iandees** [comment]
I think I solved this in #13 by switching to a different matching algorithm. Let me know if you run into it again.
