### ISSUE TITLE
Bad Foursquare/OSM Match

### ISSUE THREAD

**Issue by iandees** [osmlab/checkin-checker#16]
The system matched http://www.openstreetmap.org/node/367143762 with https://foursquare.com/v/lincolns-waffle-shop/4aafbab7f964a520956420e3

These are not the same thing.

**Comment by souperneon** [comment]
For me, it matched https://www.openstreetmap.org/edit?way=9497530 with https://foursquare.com/v/front-street/4c3511deed37a593a7ff6f03

**Comment by iandees** [comment]
I made some improvements to the query + match system that hopefully catches these sorts of problems. I'm going to close this for now and if there are other problems we should open it again.
