### ISSUE TITLE
Tell me the venue's website URL when I check in

### ISSUE THREAD

**Issue by stevevance** [osmlab/checkin-checker#24]
To speed up the process of getting primary source venue metadata that I need to add the venue to OSM, can you send me the venue's website from the Foursquare database so I can go to their website and get their address and phone number?

**Comment by iandees** [comment]
Good idea! I can do that when Foursquare has the URL.

**Comment by iandees** [comment]
I think this was fixed in 3123d52. I deployed the change, let's see if it works.

**Comment by stevevance** [comment]
I checked into a few places today, and I didn't get *any* emails.

**Comment by iandees** [comment]
Yea, I broke it and just fixed it ~1 hour ago.

**Comment by stevevance** [comment]
emails are coming in now, but I haven't checked into a place that I know has a website.

**Comment by iandees** [comment]
I just tested it and got a URL back, so I'm going to close it for now.
