### ISSUE TITLE
Tool includes private / home venues

### ISSUE THREAD

**Issue by talllguy** [osmlab/checkin-checker#3]
When I check-in to my house, I get the email. Most venues flagged as private or categorized as home, shouldn't be on OSM, because people use names like "The Love Shack" to name their homes on 4Sq:

![2015-11-19 15_10_03-inbox elliott plack gmail com](https://cloud.githubusercontent.com/assets/1827881/11282895/c36e4656-8ecf-11e5-92a4-8546adda73e4.png)

**Comment by iandees** [comment]
Fixed in 4ec7c7b6bd.
