### ISSUE TITLE
Airports

### ISSUE THREAD

**Issue by almccon** [osmlab/checkin-checker#6]
I've checked in at a few airports, and checkin-checker never finds a correspondence. Perhaps I'm just too far away from the OSM location (because airports are big) or else it's not checking for the right type of airport POI in OSM?

**Comment by iandees** [comment]
In most cases I imagine there isn't a point in OSM for the airport and the polygon for the outline is too far away from the Foursquare POI. This tool checks a [100 meter radius](https://github.com/osmlab/checkin-checker/blob/224e742/checkinchecker/checker.py#L21-L23) for all OSM types using Overpass. I bet I could bump that up to 500 meters and solve the majority of this problem.

**Comment by iandees** [comment]
I think this is fixed in #13, where I limit the OSM query to match airport-ey things and expand the search radius to cover even the biggest airports.

**Comment by almccon** [comment]
Cool! I'll keep an eye out for any changes when I next take a flight!
