### ISSUE TITLE
Email me even when the place I checked in to is already on OSM

### ISSUE THREAD

**Issue by stevevance** [osmlab/checkin-checker#7]
The first reason I want this feature is to ensure that the app works, and that my check-ins are being received. 

The second reason I want this feature is to be given the opportunity to update the information on the venue. 

Question: How do you know when a venue is added to OSM or not?

**Comment by iandees** [comment]
I made a change in 039b695 to send an email when a match happens, asking some questions to improve OSM.

**Comment by aawiseman** [comment]
Just got this email, it's awesome!  Thanks for adding!

**Comment by iandees** [comment]
Awesome! If you can think of other questions to ask in this email, let me know.
